=== Christian-Gimenez/Ejercicios_1DAW/LenguajesDeMarcas_(HTML-CSS-XML)/XML/PracticaExamenXML-DTD-XSD/ej2.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name+, age+, department+, salary+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age ANY>
<!ELEMENT department ANY>
<!ELEMENT salary ANY>
<!ATTLIST employee id NMTOKEN #REQUIRED>

=== Christian-Gimenez/Ejercicios_1DAW/LenguajesDeMarcas_(HTML-CSS-XML)/XML/PracticaExamenXML-DTD-XSD/ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE employees SYSTEM "ej2.dtd">-->
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ej2.xsd">
  <employee id="001">
    <name>John Doe</name>
    <age>30</age>
    <department>Marketing</department>
    <salary>50000</salary>
  </employee>
  <employee id="002">
    <name>Jane Smith</name>
    <age>35</age>
    <department>Finance</department>
    <salary>60000</salary>
  </employee>
</employees>
