=== Christian-Gimenez/Ejercicios_1DAW/LenguajesDeMarcas_(HTML-CSS-XML)/XML/ExamenXML_3P/Ejercicio2.dtd
<!ELEMENT examen (persona)*>
    <!ELEMENT persona (nombre+, nacimiento?, direccion*, (varon | hembra)+)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT nacimiento EMPTY>
            <!ATTLIST nacimiento dia CDATA #IMPLIED>
            <!ATTLIST nacimiento mes CDATA #IMPLIED>
            <!ATTLIST nacimiento anyo CDATA #IMPLIED>
        <!ELEMENT direccion (calle, poblacion, provincia, cpostal)+>
            <!ELEMENT calle (#PCDATA)>
            <!ELEMENT poblacion (#PCDATA)>
            <!ELEMENT provincia (#PCDATA)>
            <!ELEMENT cpostal (#PCDATA)>
        <!ELEMENT varon EMPTY>
        <!ELEMENT hembra EMPTY>

=== Christian-Gimenez/Ejercicios_1DAW/LenguajesDeMarcas_(HTML-CSS-XML)/XML/ExamenXML_3P/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "Ejercicio2.dtd">
<!-- Christian Miguel Giménez Puerma 1ºDAW-->
<examen>
    <persona>
        <nombre>Juan Pardo</nombre>
        <nacimiento dia="10" mes="Abril" anyo="1982" />
        <direccion>
            <calle>Caoba, 1</calle>
            <poblacion>Madrid</poblacion>
            <provincia>Madrid</provincia>
            <cpostal>28005</cpostal>
        </direccion>
        <varon />
    </persona>

    <persona>

        <nombre>María Lopez</nombre>
        <direccion>
            <calle>Avda. Roncato 1</calle>
            <poblacion>Illescas</poblacion>
            <provincia>Toledo</provincia>
            <cpostal>45200</cpostal>
        </direccion>
        <direccion>
            <calle>Paseo de la Esperanza 15, 1ºA</calle>
            <poblacion>Madrid</poblacion>
            <provincia>Madrid</provincia>
            <cpostal>28031</cpostal>
        </direccion>
        <hembra />
    </persona>
</examen>
