=== Christian-Gimenez/Ejercicios_1DAW/LenguajesDeMarcas_(HTML-CSS-XML)/XML/XSD/almacen-rest00.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="almacen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="responsable"/>
                <xs:element name="prod" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="30"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:fractionDigits value="2"/>
                                        <xs:minExclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="categoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Ebanisteria"/>
                                        <xs:enumeration value="Electricidad"/>
                                        <xs:enumeration value="Pintura"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="descuento">
                                <xs:simpleType>
                                    <xs:restriction base="xs:nonNegativeInteger">
                                        <xs:maxInclusive value="100"></xs:maxInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                        <xs:attribute name="id">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:length value="4"/>
                                    <xs:pattern value="[A-Z][0-9]{3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== Christian-Gimenez/Ejercicios_1DAW/LenguajesDeMarcas_(HTML-CSS-XML)/XML/XSD/xsd-restrictions.xml
<?xml version="1.0" encoding="UTF-8"?>
<almacen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./almacen-rest00.xsd">
    <responsable/>
    <prod id="A001">
        <nombre>Sierra</nombre>
        <precio>23.95</precio>
        <categoria>Ebanisteria</categoria>
        <descuento>5</descuento>
    </prod>

    <prod id="B001">
        <nombre>Led 5w</nombre>
        <precio>6.95</precio>
        <categoria>Electricidad</categoria>
        <descuento>0</descuento>
    </prod>

</almacen>
